baseURL = 'https://gigabug.org/'
languageCode = 'en-US'

[[menus.main]]
name = 'About'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Research'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
